### PR TITLE
Files data values

### PR DESCRIPTION
**Pull request by butofleury**

### CODE REVIEW

**Comment by mestachs** [comment]
any chance to find one running example on play of a file type data element and use it in sample invoice ?

**Comment by butofleury** [comment]
> any chance to find one running example on play of a file type data element and use it in sample invoice ?

**Comment by butofleury** [comment]
Thanks, I will add an example on play!

**Comment by mestachs** [comment]
tried to find some data but couldn't find some. and they looked like "word document" so not really our usecase

**Pull request merged**
